### ISSUE TITLE
Мелкие недочёты в блоке .faq__list

### ISSUE THREAD

**Issue by mayrlex** [maxdenaro/verstaem.online#1]
- При **открытии/закрытии** аккордеона на главной странице в разделе **FAQ**,  скругление границ правого и левого нижних углов обнуляется после появления контента. Выглядит это не очень красиво.
  <details>
      <summary>Превью</summary>
      <img src='https://user-images.githubusercontent.com/50993607/233926632-ed9d097a-0963-4e09-8a99-7de89c0c173d.png'>
  </details>
- Нажатие на **.accordion__content** левой кнопкой мыши влечёт за собой закрытие всего элемента аккордеона. Что для UX точно не в лучшую сторону.

**Comment by maxdenaro** [comment]
Привет!
Да, в курсе этих вещей. Пока решил оставить так, все же faq тут не самое важное) Но в бэклоге лежит. Спасибо)

**Comment by maxdenaro** [comment]
Баг пофикшен.
