### ISSUE TITLE
Возможность отфильтровать посты в блоге по авторству. 

### ISSUE THREAD

**Issue by karnauhmax** [maxdenaro/verstaem.online#2]
Было бы неплохо иметь возможность отфильтровать посты, по автору. К примеру: Я прочитал замечательную статью на сайте от замечательного автора, и мне стало интересно почитать больше статей под авторством этого человека. 

Референс для большей наглядности : 

https://css-tricks.com/some-cross-browser-devtools-features-you-might-not-know/

https://css-tricks.com/author/pankajparashar/

<img width="1398" alt="Снимок экрана 2023-05-16 в 22 26 03" src="https://github.com/maxdenaro/verstaem.online/assets/91369724/6271745d-fc20-40f1-bade-1b7588827a91">

<img width="1396" alt="Снимок экрана 2023-05-16 в 22 27 21" src="https://github.com/maxdenaro/verstaem.online/assets/91369724/306fe7ee-4650-4914-a9c5-e72662beb0eb">

На данном этапе, когда статей на сайте не так уж и много, решение может показаться не особо нужным, однако чем больше будет рости сайт и соответственно кол-во статей, тем больше нужно будет данное масштабируемое решение на мой взгляд.

**Comment by maxdenaro** [comment]
Привет! Да-да, я писал уже про это) Как будет больше статей\авторов - добавлю это
